CREATE SEQUENCE ESTADOS_SEQ;

CREATE TABLE ESTADOS(
                         ID INTEGER DEFAULT ESTADOS_SEQ.NEXTVAL NOT NULL,
                         NOME VARCHAR2(100) NOT NULL,
                         UF VARCHAR2(50) UNIQUE NOT NULL,
                         CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         PRIMARY KEY(ID)
);