CREATE SEQUENCE RUAS_SEQ;

CREATE TABLE RUAS(
                        ID INTEGER DEFAULT RUAS_SEQ.NEXTVAL NOT NULL,
                        ID_BAIRRO INTEGER NOT NULL,
                        NOME VARCHAR2(50) UNIQUE NOT NULL,
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY(ID),
                        CONSTRAINT FK_RUAS FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRROS (ID)
);