CREATE SEQUENCE TIPOS_COLETAS_SEQ;

CREATE TABLE TIPOS_COLETAS(
                     ID INTEGER DEFAULT TIPOS_COLETAS_SEQ.NEXTVAL NOT NULL,
                     DESCRICAO VARCHAR2(100) NOT NULL,
                     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                     PRIMARY KEY(ID)
);