CREATE SEQUENCE BAIRROS_SEQ;

CREATE TABLE BAIRROS(
                        ID INTEGER DEFAULT BAIRROS_SEQ.NEXTVAL NOT NULL,
                        ID_REGIAO INTEGER NOT NULL,
                        NOME VARCHAR2(50) UNIQUE NOT NULL,
                        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        PRIMARY KEY(ID),
                        CONSTRAINT FK_BAIRROS FOREIGN KEY (ID_REGIAO) REFERENCES REGIOES (ID)
);